/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.wrangler.generated.json --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: afb96593ebf36fad01b533f66d8bd084)
interface __BaseEnv_CloudflareBindings {
	ENCLAVE_MTLS: Fetcher;
	TEAM_DOMAIN: string;
	POLICY_AUD: string;
	ENCLAVE_ORIGIN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEAM_DOMAIN" | "POLICY_AUD" | "ENCLAVE_ORIGIN">> {}
}
